Update ld.so.conf so java libraries can be loaded. Fixes #18.
wpilibsuite/java-installer pull request #19
Opened 2016-12-12 05:55 UTC by sciencewhiz

2016-12-12 05:55 UTC, frcjenkins commented
Can one of the admins verify this patch?

2016-12-12 17:16 UTC, 333fred commented
@frcjenkins ok to test

2016-12-12 17:20 UTC, 333fred requested changes
I don't want to reboot the robot without informing the user that it's getting rebooted, and log it.

2016-12-12 17:20 UTC, 333fred commented on src/main/java/edu/wpi/first/wpilib/javainstaller/controllers/DeployController.java
>          executeCommand(roboRioSession, "rm " + JRE_TGZ_LOCATION, "Could not clean up. The roboRIO MIGHT be ok to use, but you should submit the error logs anyway");
We should log and display the reboot to the user. The command exits instantly, so we should update the above command label text to be "Cleaning up installer files and rebooting robot", and perhaps add an artificial second or two delay so the user can see it. We should also add another log line for the reboot execution.

2016-12-12 18:48 UTC, sciencewhiz commented on src/main/java/edu/wpi/first/wpilib/javainstaller/controllers/DeployController.java
>          executeCommand(roboRioSession, "rm " + JRE_TGZ_LOCATION, "Could not clean up. The roboRIO MIGHT be ok to use, but you should submit the error logs anyway");
It should be possible to just run ldconfig, instead of rebooting.

2016-12-13 16:03 UTC, sciencewhiz commented
This patch gets java running, but isn't enough to run a full robot program 

`Exception in thread "main" java.lang.UnsatisfiedLinkError: no wpilibJavaJNI in java.library.path
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1857)
        at java.lang.Runtime.loadLibrary0(Runtime.java:870)
        at java.lang.System.loadLibrary(System.java:1119)
        at edu.wpi.first.wpilibj.hal.JNIWrapper.<clinit>(JNIWrapper.java:22)
        at edu.wpi.first.wpilibj.RobotBase.initializeHardwareConfiguration(RobotBase.java:165)
        at edu.wpi.first.wpilibj.RobotBase.main(RobotBase.java:187)
`

2016-12-13 16:08 UTC, 333fred commented
We probably need to add /usr/local/frc/lib as well.

2016-12-13 16:45 UTC, sciencewhiz commented
/usr/local/frc/lib is included in frc_libs.conf, which is in the image.

2016-12-13 22:17 UTC, ThadHouse commented
@sciencewhiz Were you running a deploy from eclipse when you saw that error? We see that error if we just try and run the jar directly, since by default Java doesn't listen to the other .conf files. Our deploy sets the LD_LIBRARY_PATH to point to /usr/local/frc/lib before running the robot executable.

2016-12-14 01:50 UTC, sciencewhiz commented
It was running robotCommand, which I'm pretty sure has the LD_LIBRARY_PATH

2016-12-14 04:32 UTC, 333fred commented
I got it to work by using `-Djava.library.path=/usr/local/frc/lib` instead of putting `/usr/local/frc/lib` on LD_LIBRARY_PATH. Apparently when Java searches `LD_LIBRARY_PATH`, it doesn't respect `/etc/ld.so.conf`.

2016-12-14 04:54 UTC, 333fred approved these changes

2016-12-14 04:55 UTC, 333fred commented
Submitted https://github.com/wpilibsuite/EclipsePlugins/pull/66 to address the other half of this issue.

2016-12-14 06:48 UTC, merged